const wordList = [
  {"english": "a schoolmate", "chinese": "一位同校同學"},
  {"english": "a husband", "chinese": "一位先生 / 丈夫"},
  {"english": "a wife", "chinese": "一位太太 / 妻子"},
  {"english": "old", "chinese": "老的 / 舊的"},
  {"english": "a year", "chinese": "一年"},
  {"english": "where", "chinese": "哪裡"},
  {"english": "a classroom", "chinese": "一間教室"},
  {"english": "here", "chinese": "這裡"},
  {"english": "home", "chinese": "家"},
  {"english": "right here", "chinese": "就在這裡"},
  {"english": "right there", "chinese": "就在那裡"},
  {"english": "at", "chinese": "在"},
  {"english": "work", "chinese": "工作的地方"},
  {"english": "over here", "chinese": "這裡"},
  {"english": "over there", "chinese": "那裡"},
  {"english": "out", "chinese": "外出了 / 出去了"},
  {"english": "to pick up", "chinese": "撿起來 / 拿起來"},
  {"english": "to put down", "chinese": "放下"},
  {"english": "next to", "chinese": "在...的旁邊"},
  {"english": "under", "chinese": "在...的下面"},
  {"english": "happy", "chinese": "快樂的"},
  {"english": "sad", "chinese": "難過的 / 傷心的"},
  {"english": "an adjective", "chinese": "一個形容詞"},
  {"english": "a noun", "chinese": "一個名詞"},
  {"english": "cute", "chinese": "可愛的"},
  {"english": "ugly", "chinese": "醜陋的"},
  {"english": "handsome", "chinese": "英俊的"},
  {"english": "average", "chinese": "平均的 / 一般的"},
  {"english": "right", "chinese": "對的"},
  {"english": "wrong", "chinese": "錯的"},
  {"english": "tall", "chinese": "高的"},
  {"english": "short", "chinese": "矮的 / 短的"},
  {"english": "black", "chinese": "黑色"},
  {"english": "white", "chinese": "白色"},
  {"english": "blue", "chinese": "藍色"},
  {"english": "red", "chinese": "紅色"},
  {"english": "green", "chinese": "綠色"},
  {"english": "yellow", "chinese": "黃色"},
  {"english": "orange", "chinese": "橘色"},
  {"english": "brown", "chinese": "棕色 / 咖啡色"},
  {"english": "gold", "chinese": "金色"},
  {"english": "silver", "chinese": "銀色"},
  {"english": "tan", "chinese": "黃褐色"},
  {"english": "purple", "chinese": "紫色"},
  {"english": "pink", "chinese": "粉紅色"},
  {"english": "gray", "chinese": "灰色"},
  {"english": "light", "chinese": "淺色的"},
  {"english": "dark", "chinese": "深色的"},
  {"english": "a jacket", "chinese": "一件夾克"},
  {"english": "a shirt", "chinese": "一件襯衫 / 上衣"},
  {"english": "hair", "chinese": "頭髮 / 毛"},
  {"english": "a bicycle", "chinese": "一輛腳踏車"},
  {"english": "a grade", "chinese": "一個年級"},
  {"english": "first (1st)", "chinese": "第一"},
  {"english": "second (2nd)", "chinese": "第二"},
  {"english": "third (3rd)", "chinese": "第三"},
  {"english": "fourth (4th)", "chinese": "第四"},
  {"english": "fifth (5th)", "chinese": "第五"},
  {"english": "sixth (6th)", "chinese": "第六"},
  {"english": "singular", "chinese": "單數的"},
  {"english": "plural", "chinese": "複數的"},
  {"english": "pretty", "chinese": "漂亮的"},
  {"english": "irregular", "chinese": "不規則的"},
  {"english": "people", "chinese": "人們"},
  {"english": "a child", "chinese": "一位孩子"},
  {"english": "children", "chinese": "孩子們"},
  {"english": "a man", "chinese": "一位男人"},
  {"english": "men", "chinese": "男人們"},
  {"english": "a woman", "chinese": "一位女人"},
  {"english": "women", "chinese": "女人們"},
  {"english": "a foot", "chinese": "一隻腳"},
  {"english": "feet", "chinese": "腳(複數)"},
  {"english": "a tooth", "chinese": "一顆牙齒"},
  {"english": "teeth", "chinese": "牙齒(複數)"},
  {"english": "a mouse", "chinese": "一隻老鼠"},
  {"english": "loud", "chinese": "大聲的"},
  {"english": "quiet", "chinese": "安靜的"},
  {"english": "mice", "chinese": "老鼠(複數)"},
  {"english": "(a) fish", "chinese": "魚"},
  {"english": "an elementary school", "chinese": "一間小學"},
  {"english": "a junior high school", "chinese": "一間國中"},
  {"english": "a senior high school", "chinese": "一間高中"},
  {"english": "young", "chinese": "年輕的"},
  {"english": "tired", "chinese": "累的 / 疲倦的"},
  {"english": "energetic", "chinese": "有精神的"},
  {"english": "new", "chinese": "新的"},
  {"english": "a face", "chinese": "一張臉"},
  {"english": "a head", "chinese": "一顆頭"},
  {"english": "a forehead", "chinese": "一個額頭"},
  {"english": "an ear", "chinese": "一隻耳朵"},
  {"english": "an eyebrow", "chinese": "一個眉毛"},
  {"english": "an eye", "chinese": "一隻眼睛"},
  {"english": "a mouth", "chinese": "一張嘴巴"},
  {"english": "a chin", "chinese": "一個下巴"},
  {"english": "a cheek", "chinese": "一個臉頰"},
  {"english": "a nose", "chinese": "一個鼻子"},
  {"english": "a lip", "chinese": "一片嘴唇"},
  {"english": "the sky", "chinese": "天空"},
  {"english": "clean", "chinese": "乾淨的"},
  {"english": "a tongue", "chinese": "一根舌頭"},
  {"english": "grass", "chinese": "草"},
  {"english": "shy", "chinese": "害羞的"},
  {"english": "outgoing", "chinese": "外向的"},
  {"english": "lazy", "chinese": "懶惰的"},
  {"english": "hard-working", "chinese": "努力的 / 用功的"},
  {"english": "nervous", "chinese": "緊張的"},
  {"english": "confident", "chinese": "有自信的"},
  {"english": "a kiss", "chinese": "一個親吻"},
  {"english": "a watch", "chinese": "一只手錶"},
  {"english": "a dish", "chinese": "一個盤子"},
  {"english": "a wish", "chinese": "一個願望"},
  {"english": "stupid", "chinese": "愚笨的"},
  {"english": "dirty", "chinese": "髒的"},
  {"english": "busy", "chinese": "忙碌的"},
  {"english": "now", "chinese": "現在"},
  {"english": "from", "chinese": "從 / 來自"},
  {"english": "Taipei", "chinese": "台北"},
  {"english": "Taiwan", "chinese": "台灣"},
  {"english": "the Republic of China", "chinese": "中華民國"},
  {"english": "the R.O.C.", "chinese": "中華民國"},
  {"english": "healthy", "chinese": "健康的"},
  {"english": "sick", "chinese": "生病的"},
  {"english": "nice", "chinese": "好的 / 乖的"},
  {"english": "naughty", "chinese": "頑皮的"},
  {"english": "we", "chinese": "我們"},
  {"english": "diligent", "chinese": "勤勞的"},
  {"english": "art", "chinese": "美術"},
  {"english": "a class", "chinese": "一個課程"},
  {"english": "computer class", "chinese": "電腦課"},
  {"english": "Mandarin Chinese", "chinese": "國語 / 中文"},
  {"english": "math", "chinese": "數學"},
  {"english": "music", "chinese": "音樂"},
  {"english": "PE", "chinese": "體育"},
  {"english": "science", "chinese": "科學"},
  {"english": "social studies", "chinese": "社會課"},
  {"english": "easy", "chinese": "容易的"},
  {"english": "difficult", "chinese": "困難的"},
  {"english": "hard", "chinese": "困難的"},
  {"english": "useful", "chinese": "有用的"},
  {"english": "useless", "chinese": "沒有用的"},
  {"english": "a subject", "chinese": "一個科目"},
  {"english": "important", "chinese": "重要的"},
  {"english": "unimportant", "chinese": "不重要的"},
  {"english": "interesting", "chinese": "有趣的"},
  {"english": "fun", "chinese": "好玩的"},
  {"english": "boring", "chinese": "令人無聊的"},
  {"english": "an adult", "chinese": "一位大人 / 成人"},
  {"english": "America", "chinese": "美國"},
  {"english": "the USA", "chinese": "美國"},
  {"english": "Canada", "chinese": "加拿大"},
  {"english": "Australia", "chinese": "澳洲"},
  {"english": "England", "chinese": "英國"},
  {"english": "Japan", "chinese": "日本"},
  {"english": "New Zealand", "chinese": "紐西蘭"},
  {"english": "a country", "chinese": "一個國家"},
  {"english": "you (plural)", "chinese": "你們"},
  {"english": "friendly", "chinese": "友善的 / 親切的"},
  {"english": "a pet", "chinese": "一隻寵物"},
  {"english": "a neighbor", "chinese": "一位鄰居"},
  {"english": "they", "chinese": "他們"},
  {"english": "a body", "chinese": "一個身體"},
  {"english": "a neck", "chinese": "一個脖子"},
  {"english": "a shoulder", "chinese": "一個肩膀"},
  {"english": "a chest", "chinese": "一個胸部"},
  {"english": "a finger", "chinese": "一根手指"},
  {"english": "an arm", "chinese": "一隻手臂"},
  {"english": "a leg", "chinese": "一隻腿"},
  {"english": "a back", "chinese": "一個背部"},
  {"english": "a knee", "chinese": "一個膝蓋"},
  {"english": "a brain", "chinese": "一個頭腦"},
  {"english": "a heart", "chinese": "一顆心臟"},
  {"english": "a stomach", "chinese": "一個胃 / 肚子"},
  {"english": "ready", "chinese": "準備好的"},
  {"english": "to learn", "chinese": "學習"},
  {"english": "to go", "chinese": "走 / 去"},
  {"english": "a home", "chinese": "一個家"},
  {"english": "hot", "chinese": "熱的"},
  {"english": "cold", "chinese": "冷的"},
  {"english": "to take a test", "chinese": "考試"},
  {"english": "to answer", "chinese": "回答"},
  {"english": "homework", "chinese": "功課"},
  {"english": "time", "chinese": "時間"},
  {"english": "a question", "chinese": "一個問題 / 題目"},
  {"english": "to ask", "chinese": "問"},
  {"english": "very", "chinese": "非常"},
  {"english": "strong", "chinese": "強壯的"},
  {"english": "weak", "chinese": "虛弱的"},
  {"english": "a telephone", "chinese": "一個電話"},
  {"english": "a number", "chinese": "一個數字 / 號碼"},
  {"english": "a phone", "chinese": "一個電話"},
  {"english": "a T-shirt", "chinese": "一件T恤"},
  {"english": "a sweater", "chinese": "一件毛衣"},
  {"english": "a dress", "chinese": "一件洋裝"},
  {"english": "a skirt", "chinese": "一件裙子"},
  {"english": "a vest", "chinese": "一件背心"},
  {"english": "a uniform", "chinese": "一件制服"},
  {"english": "a jacket", "chinese": "一件夾克"},
  {"english": "a coat", "chinese": "一件外套"},
  {"english": "a hat", "chinese": "一頂帽子"},
  {"english": "underwear", "chinese": "內褲"},
  {"english": "an animal", "chinese": "一隻動物"},
  {"english": "our", "chinese": "我們的"},
  {"english": "a month", "chinese": "一個月"},
  {"english": "January", "chinese": "一月"},
  {"english": "February", "chinese": "二月"},
  {"english": "March", "chinese": "三月"},
  {"english": "April", "chinese": "四月"},
  {"english": "May", "chinese": "五月"},
  {"english": "June", "chinese": "六月"},
  {"english": "July", "chinese": "七月"},
  {"english": "August", "chinese": "八月"},
  {"english": "September", "chinese": "九月"},
  {"english": "October", "chinese": "十月"},
  {"english": "November", "chinese": "十一月"},
  {"english": "December", "chinese": "十二月"},
  {"english": "seventh (7th)", "chinese": "第七"},
  {"english": "eighth (8th)", "chinese": "第八"},
  {"english": "pants", "chinese": "長褲(複數)"},
  {"english": "shorts", "chinese": "短褲(複數)"},
  {"english": "shoes", "chinese": "鞋子(複數)"},
  {"english": "socks", "chinese": "襪子(複數)"},
  {"english": "sandals", "chinese": "涼鞋(複數)"},
  {"english": "glasses", "chinese": "眼鏡(複數)"},
  {"english": "large", "chinese": "大的"},
  {"english": "its", "chinese": "它的 / 牠的"},
  {"english": "to drink", "chinese": "喝"},
  {"english": "a trunk", "chinese": "一個(大象的)鼻子"},
  {"english": "a tail", "chinese": "一條尾巴"},
  {"english": "skin", "chinese": "皮膚"},
  {"english": "long", "chinese": "長的"},
  {"english": "fur", "chinese": "(動物的)毛"},
  {"english": "lucky", "chinese": "幸運的"},
  {"english": "unlucky", "chinese": "不幸運的"},
  {"english": "a pineapple", "chinese": "一顆鳳梨"},
  {"english": "your (plural)", "chinese": "你們的"},
  {"english": "a giraffe", "chinese": "一隻長頸鹿"},
  {"english": "soft", "chinese": "軟的"},
  {"english": "a date", "chinese": "一個日期"},
  {"english": "today", "chinese": "今天"},
  {"english": "to cook", "chinese": "煮"},
  {"english": "a bird", "chinese": "一隻鳥"},
  {"english": "to fly", "chinese": "飛"},
  {"english": "to dance", "chinese": "跳舞"},
  {"english": "to swim", "chinese": "游泳"},
  {"english": "a thumb", "chinese": "一隻大拇指"},
  {"english": "to watch", "chinese": "觀看"},
  {"english": "a movie", "chinese": "一部電影"},
  {"english": "to help", "chinese": "幫助"},
  {"english": "to turn on", "chinese": "打開"},
  {"english": "a banana", "chinese": "一根香蕉"},
  {"english": "a cup", "chinese": "一個杯子"},
  {"english": "soda", "chinese": "汽水"},
  {"english": "a glass", "chinese": "一個玻璃杯子"},
  {"english": "milk", "chinese": "牛奶"},
  {"english": "candy", "chinese": "糖果"},
  {"english": "some", "chinese": "一些"},
  {"english": "to ride", "chinese": "騎"},
  {"english": "to drive", "chinese": "駕駛"},
  {"english": "a car", "chinese": "一輛汽車"},
  {"english": "their", "chinese": "他們的"},
  {"english": "to write", "chinese": "寫"},
  {"english": "to read", "chinese": "讀 / 看書"},
  {"english": "a newspaper", "chinese": "一份報紙"},
  {"english": "the United States", "chinese": "美國"},
  {"english": "Canadian", "chinese": "加拿大人 / 加拿大的"},
  {"english": "American", "chinese": "美國人 / 美國的"},
  {"english": "English", "chinese": "英國人 / 英國的 / 英文"},
  {"english": "Chinese", "chinese": "中國人 / 中國的 / 中文"},
  {"english": "Japanese", "chinese": "日本人 / 日本的 / 日文"},
  {"english": "Taiwanese", "chinese": "台灣人 / 台灣的 / 台語"},
  {"english": "Australian", "chinese": "澳洲人 / 澳洲的"},
  {"english": "Korean", "chinese": "韓國人 / 韓國的 / 韓文"},
  {"english": "Thai", "chinese": "泰國人 / 泰國的 / 泰文"},
  {"english": "a seat", "chinese": "一個座位"},
  {"english": "to play (a sport)", "chinese": "打 / 踢(球類運動)"},
  {"english": "a sport", "chinese": "一種球類運動"},
  {"english": "baseball", "chinese": "棒球"},
  {"english": "basketball", "chinese": "籃球"},
  {"english": "tennis", "chinese": "網球"},
  {"english": "badminton", "chinese": "羽毛球"},
  {"english": "soccer", "chinese": "足球"},
  {"english": "football", "chinese": "足球 / 美式足球"},
  {"english": "table tennis", "chinese": "桌球"},
  {"english": "ping-pong", "chinese": "桌球 / 乒乓球"},
  {"english": "golf", "chinese": "高爾夫球"},
  {"english": "dodgeball", "chinese": "躲避球"},
  {"english": "to use", "chinese": "使用"},
  {"english": "the Internet", "chinese": "網路"},
  {"english": "self", "chinese": "自己"},
  {"english": "an introduction", "chinese": "一個介紹"},
  {"english": "good morning", "chinese": "早安"},
  {"english": "good afternoon", "chinese": "午安"},
  {"english": "good evening", "chinese": "晚上好"},
  {"english": "to introduce", "chinese": "介紹"},
  {"english": "myself", "chinese": "我自己"},
  {"english": "to have", "chinese": "有"},
  {"english": "to live", "chinese": "住"},
  {"english": "an apartment", "chinese": "住宅(公寓)的一戶"},
  {"english": "to go to ... school", "chinese": "上學"},
  {"english": "favorite", "chinese": "最喜歡的"},
  {"english": "to like", "chinese": "喜歡"},
  {"english": "Minsheng", "chinese": "民生"},
  {"english": "east", "chinese": "東"},
  {"english": "a road", "chinese": "一條路"},
  {"english": "kind", "chinese": "仁慈的"},
  {"english": "mean", "chinese": "兇惡的"},
  {"english": "patient", "chinese": "有耐心的"},
  {"english": "impatient", "chinese": "沒有耐心的"},
  {"english": "strange", "chinese": "奇怪的"},
  {"english": "thank you very much", "chinese": "非常謝謝你"},
  {"english": "to play (a musical instrument)", "chinese": "演奏 / 拉 / 吹 / 彈 / 打"},
  {"english": "musical", "chinese": "音樂的"},
  {"english": "an instrument", "chinese": "一個樂器"},
  {"english": "a flute", "chinese": "一支長笛"},
  {"english": "a guitar", "chinese": "一把吉他"},
  {"english": "a drum", "chinese": "一面鼓"},
  {"english": "a recorder", "chinese": "一支直笛"},
  {"english": "a violin", "chinese": "一把小提琴"},
  {"english": "a piano", "chinese": "一架鋼琴"},
  {"english": "a trumpet", "chinese": "一支喇叭 / 小號"},
  {"english": "me", "chinese": "我(受詞)"},
  {"english": "you", "chinese": "你(受詞)"},
  {"english": "him", "chinese": "他(受詞)"},
  {"english": "her", "chinese": "她(受詞)"},
  {"english": "it", "chinese": "它 / 牠(受詞)"},
  {"english": "to hear", "chinese": "聽到 / 聽見"},
  {"english": "to see", "chinese": "看到 / 看見"},
  {"english": "us", "chinese": "我們(受詞)"},
  {"english": "you (plural)", "chinese": "你們(受詞)"},
  {"english": "them", "chinese": "他們(受詞)"},
  {"english": "Keelung", "chinese": "基隆"},
  {"english": "north", "chinese": "北"},
  {"english": "south", "chinese": "南"},
  {"english": "west", "chinese": "西"},
  {"english": "a street", "chinese": "一條街"},
  {"english": "parents", "chinese": "父母們"},
  {"english": "comfortable", "chinese": "舒適的 / 舒服的"},
  {"english": "because", "chinese": "因為"},
  {"english": "too", "chinese": "太"},
  {"english": "a shark", "chinese": "一隻鯊魚"},
  {"english": "a cookie", "chinese": "一個餅乾"},
  {"english": "dangerous", "chinese": "危險的"},
  {"english": "ice cream", "chinese": "冰淇淋"},
  {"english": "pizza", "chinese": "披薩"},
  {"english": "Coke", "chinese": "可口可樂"},
  {"english": "iced-tea", "chinese": "冰茶"},
  {"english": "(a) cake", "chinese": "(一個)蛋糕"},
  {"english": "sweet", "chinese": "甜的"},
  {"english": "a lot of", "chinese": "很多"},
  {"english": "a few", "chinese": "幾個"},
  {"english": "any", "chinese": "任何"},
  {"english": "to know", "chinese": "認識 / 知道"},
  {"english": "an answer", "chinese": "一個答案"},
  {"english": "an only child", "chinese": "(一位)唯一的 小孩 / 獨生子"},
  {"english": "a toy", "chinese": "一個玩具"},
  {"english": "a dictionary", "chinese": "一本字典"},
  {"english": "to draw", "chinese": "(用筆)畫"},
  {"english": "to skate", "chinese": "溜冰"},
  {"english": "to study", "chinese": "學習"},
  {"english": "to jog", "chinese": "慢跑"},
  {"english": "Mahjong", "chinese": "麻將"},
  {"english": "to sing", "chinese": "唱歌"},
  {"english": "to want", "chinese": "想要"},
  {"english": "a video game", "chinese": "一個電動遊戲"},
  {"english": "sneakers", "chinese": "運動鞋(複數)"},
  {"english": "a game", "chinese": "一個遊戲"},
  {"english": "to know how to", "chinese": "知道如何"},
  {"english": "Chinese checkers", "chinese": "跳棋"},
  {"english": "with", "chinese": "跟"},
  {"english": "together", "chinese": "在一起"},
  {"english": "grandparents", "chinese": "祖父母"},
  {"english": "to understand", "chinese": "了解 / 懂 / 明白"},
  {"english": "to mean", "chinese": "...的意思是"},
  {"english": "international", "chinese": "國際的"},
  {"english": "a language", "chinese": "一種語言"},
  {"english": "How many", "chinese": "多少 / 幾個"},
  {"english": "a piece", "chinese": "一片 / 一塊"},
  {"english": "to be", "chinese": "當"},
  {"english": "next", "chinese": "下一個"},
  {"english": "many", "chinese": "很多(複數的)"},
  {"english": "to kiss", "chinese": "親吻"},
  {"english": "to teach", "chinese": "教"},
  {"english": "to wash", "chinese": "洗"},
  {"english": "to fix", "chinese": "修理"},
  {"english": "to brush", "chinese": "刷 / 梳"},
  {"english": "How much", "chinese": "多少(不可數)"},
  {"english": "much", "chinese": "很多(不可數)"},
  {"english": "to chase", "chinese": "追"},
  {"english": "to change", "chinese": "改變 / 換"},
  {"english": "to practice", "chinese": "練習"},
  {"english": "o'clock", "chinese": "...點鐘"},
  {"english": "mine", "chinese": "我的+noun"},
  {"english": "yours", "chinese": "你的+noun"},
  {"english": "his", "chinese": "他的+noun"},
  {"english": "hers", "chinese": "她的+noun"},
  {"english": "its", "chinese": "它的 / 牠的+noun"},
  {"english": "polite", "chinese": "有禮貌的"},
  {"english": "a lady", "chinese": "一位女士"},
  {"english": "rude", "chinese": "粗魯的"},
  {"english": "impolite", "chinese": "沒有禮貌的"},
  {"english": "generous", "chinese": "慷慨的 / 大方的"},
  {"english": "greedy", "chinese": "貪心的"},
  {"english": "a guy", "chinese": "一位男生"},
  {"english": "Mr.", "chinese": "先生"},
  {"english": "Mrs.", "chinese": "太太"},
  {"english": "Miss", "chinese": "小姐"},
  {"english": "Ms.", "chinese": "女士"},
  {"english": "ours", "chinese": "我們的+noun"},
  {"english": "yours (plural)", "chinese": "你們的+noun"},
  {"english": "theirs", "chinese": "他們的+noun"},
  {"english": "to wake up", "chinese": "醒來"},
  {"english": "usually", "chinese": "通常"},
  {"english": "in the morning", "chinese": "在早上"},
  {"english": "in the afternoon", "chinese": "在下午"},
  {"english": "in the evening", "chinese": "在傍晚"},
  {"english": "at night", "chinese": "在晚上"},
  {"english": "to work", "chinese": "工作"},
  {"english": "to get to (a place)", "chinese": "到達(一個地方)"},
  {"english": "to walk", "chinese": "走路"},
  {"english": "to take (a bus)", "chinese": "搭(公車)"},
  {"english": "to take (ST/SB to SP)", "chinese": "帶去"},
  {"english": "a taxi", "chinese": "一輛計程車"},
  {"english": "the MRT", "chinese": "(台灣的)捷運"},
  {"english": "a school bus", "chinese": "一輛校車"},
  {"english": "a motorcycle", "chinese": "一輛摩托車"},
  {"english": "a bus", "chinese": "一輛公車"},
  {"english": "to get up", "chinese": "起來"},
  {"english": "a meal", "chinese": "一個餐 / 一頓飯"},
  {"english": "breakfast", "chinese": "早餐"},
  {"english": "lunch", "chinese": "午餐"},
  {"english": "dinner", "chinese": "晚餐"},
  {"english": "(a) dessert", "chinese": "(一個)飯後甜點"},
  {"english": "a snack", "chinese": "一個點心"},
  {"english": "weather", "chinese": "天氣"},
  {"english": "warm", "chinese": "溫暖的"},
  {"english": "cool", "chinese": "涼爽的"},
  {"english": "sunny", "chinese": "晴天"},
  {"english": "cloudy", "chinese": "多雲的"},
  {"english": "rainy", "chinese": "多雨的"},
  {"english": "raining", "chinese": "正在下雨"},
  {"english": "beautiful", "chinese": "美麗的"},
  {"english": "a typhoon", "chinese": "一個颱風"},
  {"english": "windy", "chinese": "多風的"},
  {"english": "as adj as", "chinese": "像什麼一樣"},
  {"english": "a television", "chinese": "一台電視"},
  {"english": "brave", "chinese": "勇敢的"},
  {"english": "to come", "chinese": "來"},
  {"english": "on my way", "chinese": "去什麼地方的路上"},
  {"english": "McDonald's", "chinese": "麥當勞"},
  {"english": "yourself", "chinese": "你自己"},
  {"english": "himself", "chinese": "他自己"},
  {"english": "herself", "chinese": "她自己"},
  {"english": "itself", "chinese": "它自己"},
  {"english": "ourselves", "chinese": "我們自己"},
  {"english": "yourselves", "chinese": "你們自己"},
  {"english": "themselves", "chinese": "他們自己"},
  {"english": "ever", "chinese": "有時候"},
  {"english": "always", "chinese": "總是"},
  {"english": "often", "chinese": "常常"},
  {"english": "sometimes", "chinese": "有時候"},
  {"english": "seldom", "chinese": "很少"},
  {"english": "rarely", "chinese": "很少"},
  {"english": "never", "chinese": "從不 / 都沒有"},
  {"english": "before", "chinese": "在...之前"},
  {"english": "to review", "chinese": "複習"},
  {"english": "to hug", "chinese": "擁抱"},
  {"english": "to start", "chinese": "開始"},
  {"english": "to buy", "chinese": "買"},
  {"english": "ninth (9th)", "chinese": "第九"},
  {"english": "tenth (10th)", "chinese": "第十"},
  {"english": "eleventh (11th)", "chinese": "第十一"},
  {"english": "twelfth (12th)", "chinese": "第十二"},
  {"english": "thirteenth (13th)", "chinese": "第十三"},
  {"english": "fourteenth (14th)", "chinese": "第十四"},
  {"english": "fifteenth (15th)", "chinese": "第十五"},
  {"english": "sixteenth (16th)", "chinese": "第十六"},
  {"english": "seventeenth (17th)", "chinese": "第十七"},
  {"english": "eighteenth (18th)", "chinese": "第十八"},
  {"english": "nineteenth (19th)", "chinese": "第十九"},
  {"english": "twentieth (20th)", "chinese": "第二十"},
  {"english": "twenty-first (21st)", "chinese": "第二十一"},
  {"english": "twenty-second (22nd)", "chinese": "第二十二"},
  {"english": "twenty-third (23rd)", "chinese": "第二十三"},
  {"english": "twenty-fourth (24th)", "chinese": "第二十四"},
  {"english": "twenty-fifth (25th)", "chinese": "第二十五"},
  {"english": "twenty-sixth (26th)", "chinese": "第二十六"},
  {"english": "twenty-seventh (27th)", "chinese": "第二十七"},
  {"english": "twenty-eighth (28th)", "chinese": "第二十八"},
  {"english": "twenty-ninth (29th)", "chinese": "第二十九"},
  {"english": "thirtieth (30th)", "chinese": "第三十"},
  {"english": "thirty-first (31st)", "chinese": "第三十一"},
  {"english": "a birthday", "chinese": "一個生日"}
];
